source 'https://rubygems.org'

# Specify your gem's dependencies in data_extraction.gemspec
#
#
gem 'guard-rspec', require: false
gem 'rubocop', require: false

gem 'pry'

gem 'rdf', '~> 1.1.3'
gem 'rdf-turtle', '~> 1.1.3'
gem 'json-ld', '~> 1.1.2'
gem 'json-schema', '~> 2.2.2'
gem 'sparql', '~> 1.1.3', git: 'git://github.com/ruby-rdf/sparql.git', branch: 'develop'
gem 'json-generator', '~> 0.1.0'
gem 'rdf-rdfxml', '~> 1.1.0.1'
gem 'rest-client', '~> 1.8.0'
gem 'elasticsearch', '~> 1.0.12'
gem 'nokogiri', '~> 1.6.6.2'
gem 'faker', '~> 1.4.3'

gemspec
