

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head><meta charset="utf-8" /><title>
	Main Notice Search Page - Sell2Wales
</title>
        <meta name="Keywords" content="Sell2Wales: tenders, ojeu, ojec, public sector contract opportunities, private sector contracts, Wales" />
        <meta name="Description" content="Welcome to Sell2Wales, an initiative from the Welsh Government helping SMEs work successfully with the public sector." />
    <meta name="verify-v1" content="h3zIB0xAx0s1OfplreVF21lVPDlWUGUMqWoFlowRDew=" />
    <script src="/Scripts/common.js"></script>
    <!--[if lt IE 9]>
        <script src="/Scripts/html5shiv.js"></script>
    <![endif]-->
    <link href="/Styles/Site.css?v=1" rel="stylesheet" /><link href="/RadControls/WalesTabs/TabStrip.WalesTabs.css" rel="stylesheet" /><link href="../Skin_Telerik/TreeView.Skin_Telerik.css" rel="stylesheet" />
   <script>
       (function (i, s, o, g, r, a, m) {
           i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
               (i[r].q = i[r].q || []).push(arguments)
           }, i[r].l = 1 * new Date(); a = s.createElement(o),
           m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
       })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

       ga('create', 'UA-1431382-28', 'sell2wales.gov.uk');
       ga('send', 'pageview');

</script>
</head>
<body>
    <form method="post" action="search_mainpage.aspx" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE1NDkzNjQ1MjcPFgIeDUluY2x1ZGVBd2FyZHNnFgJmDw8WAh4JUGFnZVRpdGxlBSRNYWluIE5vdGljZSBTZWFyY2ggUGFnZSAtIFNlbGwyV2FsZXNkFgICAw9kFggCBw8PFgYeBFRleHQFBkxvZyBpbh4HVG9vbFRpcAUGTG9nIGluHgtOYXZpZ2F0ZVVybAUSL0FjY2Vzcy9Mb2dpbi5hc3B4ZGQCCQ8PFgIfBAUiaHR0cDovL3d3dy5nd2VydGh3Y2hpZ3ltcnUuZ292LnVrL2RkAgsPZBYMAgEPFgIeB1Zpc2libGVnZAIFD2QWBgIBDw8WAh8CBQMyNTVkZAIFDxBkEBUGATEBMgEzATQBNQE2FQYBMQEyATMBNAE1ATYUKwMGZ2dnZ2dnZGQCBw8PFgIfAgUBNmRkAgcPPCsAEQMADxYIHgtBbGxvd1BhZ2luZ2ceCFBhZ2VTaXplAjMeC18hRGF0YUJvdW5kZx4LXyFJdGVtQ291bnQCgAJkARAWABYAFgAMFCsAABYCZg9kFmgCAQ8PZBYCHgVzdHlsZQUNZGlzcGxheTpub25lOxYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1TRVAwMDY4ODMQTXVzY3Vsb3NrZWxldGFsLhBNdXNjdWxvc2tlbGV0YWwuCVNFUDAwNjg4MzFOSFMgRGFybGluZ3RvbiBDbGluaWNhbCBDb21taXNzaW9uaW5nIEdyb3VwIChDQ0cpABhQcmlvciBJbmZvcm1hdGlvbiBOb3RpY2VkAgIPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMzJRU3VwcGx5LCBkZWxpdmVyLCBlcmVjdCwgdGVzdCBhbmQgY29tbWlzc2lvbiBvZiBSdWJiZXIgVHlyZWQgR2FudHJ5IENyYW5lcyAoUlRHcykuUVN1cHBseSwgZGVsaXZlciwgZXJlY3QsIHRlc3QgYW5kIGNvbW1pc3Npb24gb2YgUnViYmVyIFR5cmVkIEdhbnRyeSBDcmFuZXMgKFJUR3MpLglKVU4wOTAzMzITUEQgVGVlc3BvcnQgTGltaXRlZAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIDD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMzMzKFJhaWx3YXkgd2Vic2l0ZXMgZm9yIFRoZSBHby1BaGVhZCBHcm91cC4oUmFpbHdheSB3ZWJzaXRlcyBmb3IgVGhlIEdvLUFoZWFkIEdyb3VwLglKVU4wOTAzMzMWR28gQWhlYWQgR3JvdXAgSG9sZGluZwkwMy1KdWwtMTUPQ29udHJhY3QgTm90aWNlZAIED2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMzM0ZFRoZSBwcm92aXNpb24gb2YgYSBMb3NzIEFkanVzdGVyIHRvIHNlcnZpY2UgdGhlIHdob2xlIG9mIHRoZSBBbmdsaWFuIFdhdGVyIHJlZ2lvbiwgZm9yIG1haW5seSBwdWJsaWNkVGhlIHByb3Zpc2lvbiBvZiBhIExvc3MgQWRqdXN0ZXIgdG8gc2VydmljZSB0aGUgd2hvbGUgb2YgdGhlIEFuZ2xpYW4gV2F0ZXIgcmVnaW9uLCBmb3IgbWFpbmx5IHB1YmxpYwlKVU4wOTAzMzQeQW5nbGlhbiBXYXRlciBTZXJ2aWNlcyBMaW1pdGVkABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAgUPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMzEXTlJIUy0yMDE0LVRCQyBHcmluZGluZy4XTlJIUy0yMDE0LVRCQyBHcmluZGluZy4JSlVOMDkwMzMxF05ldHdvcmsgUmFpbCBIaWdoIFNwZWVkABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAgYPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMTE+S1BMLTEwTVcgRW5lcmd5IFN0b3JhZ2UgRmFjaWxpdHkg4oCUIExvdCAyIEludmVydGVyIEVxdWlwbWVudC4+S1BMLTEwTVcgRW5lcmd5IFN0b3JhZ2UgRmFjaWxpdHkg4oCUIExvdCAyIEludmVydGVyIEVxdWlwbWVudC4JSlVOMDkwMzExFUFFUyBLaWxyb290IFBvd2VyIEx0ZAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIHD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjg5FkluYm91bmQgTWFpbCBDb250cmFjdC4WSW5ib3VuZCBNYWlsIENvbnRyYWN0LglKVU4wOTAyODkkTm9ydGggSGVydGZvcmRzaGlyZSBEaXN0cmljdCBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAggPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMzBbUHJvdmlzaW9uIG9mIGFuIEludGVncmF0ZWQgQ29tbXVuaXR5IEFkdWx0IERydWcgYW5kIEFsY29ob2wgUmVjb3ZlcnkgYW5kIFRyZWF0bWVudCBTZXJ2aWNlLltQcm92aXNpb24gb2YgYW4gSW50ZWdyYXRlZCBDb21tdW5pdHkgQWR1bHQgRHJ1ZyBhbmQgQWxjb2hvbCBSZWNvdmVyeSBhbmQgVHJlYXRtZW50IFNlcnZpY2UuCUpVTjA5MDMzMB5HbG91Y2VzdGVyc2hpcmUgQ291bnR5IENvdW5jaWwAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCCQ9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDMxMFlEeW5hbWljIFB1cmNoYXNpbmcgU3lzdGVtIGZvciBMb2NhbCBhbmQgSG9tZSB0byBTY2hvb2wgVHJhbnNwb3J0IOKAlCBGdXJ0aGVyIENvbXBldGl0aW9uLllEeW5hbWljIFB1cmNoYXNpbmcgU3lzdGVtIGZvciBMb2NhbCBhbmQgSG9tZSB0byBTY2hvb2wgVHJhbnNwb3J0IOKAlCBGdXJ0aGVyIENvbXBldGl0aW9uLglKVU4wOTAzMTAiTm9ydGggTGluY29sbnNoaXJlIEJvcm91Z2ggQ291bmNpbAkwOS1KdWwtMTUPQ29udHJhY3QgTm90aWNlZAIKD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjg4QlB1cmNoYXNlIGFuIGUtU29jaWFsIENhcmUgUHVyY2hhc2luZyBTeXN0ZW0gZm9yIEFkdWx0IFNvY2lhbCBDYXJlLkJQdXJjaGFzZSBhbiBlLVNvY2lhbCBDYXJlIFB1cmNoYXNpbmcgU3lzdGVtIGZvciBBZHVsdCBTb2NpYWwgQ2FyZS4JSlVOMDkwMjg4FUlzbGUgb2YgV2lnaHQgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAILD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjg3XE11bHRpcGxlIEZyYW1ld29yayBBZ3JlZW1lbnQgZm9yIFRyYW5zcG9ydCBQbGFubmluZywgTW9kZWxsaW5nIGFuZCBBdWRpdCBTZXJ2aWNlcyAyMDExLTIwMTQuXE11bHRpcGxlIEZyYW1ld29yayBBZ3JlZW1lbnQgZm9yIFRyYW5zcG9ydCBQbGFubmluZywgTW9kZWxsaW5nIGFuZCBBdWRpdCBTZXJ2aWNlcyAyMDExLTIwMTQuCUpVTjA5MDI4NxJUcmFuc3BvcnQgU2NvdGxhbmQAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCDA9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI4NlJTV0NTVSDigJQgU29tZXJzZXQgQ0NHLU5IUyAxMTEgYW5kIFByaW1hcnkgQ2FyZSBPdXQgb2YgSG91cnMgc2VydmljZXMgaW4gdHdvIExPVFMuUlNXQ1NVIOKAlCBTb21lcnNldCBDQ0ctTkhTIDExMSBhbmQgUHJpbWFyeSBDYXJlIE91dCBvZiBIb3VycyBzZXJ2aWNlcyBpbiB0d28gTE9UUy4JSlVOMDkwMjg2KU5IUyBTb21lcnNldCBDbGluaWNhbCBDb21taXNzaW9uaW5nIEdyb3VwABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAg0PZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyODUgUHJvdmlzaW9uIG9mIExvY2FsIEJ1cyBTZXJ2aWNlcy4gUHJvdmlzaW9uIG9mIExvY2FsIEJ1cyBTZXJ2aWNlcy4JSlVOMDkwMjg1LVNvdXRoIFlvcmtzaGlyZSBQYXNzZW5nZXIgVHJhbnNwb3J0IEV4ZWN1dGl2ZQAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIOD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMzA4SEh1bWJlciBVbml2ZXJzaXR5IFRlY2huaWNhbCBDb2xsZWdlIExlYWRlcnNoaXAgYW5kIEltcHJvdmVtZW50IFNlcnZpY2VzLkhIdW1iZXIgVW5pdmVyc2l0eSBUZWNobmljYWwgQ29sbGVnZSBMZWFkZXJzaGlwIGFuZCBJbXByb3ZlbWVudCBTZXJ2aWNlcy4JSlVOMDkwMzA4Ckh1bWJlciBVVEMAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCDw9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDMwOUBQcm92aXNpb24gb2YgTm9uIExpZmUgSW5zdXJhbmNlIFNlcnZpY2VzIGV4Y2x1ZGluZyBicm9raW5nIDIwMTUuQFByb3Zpc2lvbiBvZiBOb24gTGlmZSBJbnN1cmFuY2UgU2VydmljZXMgZXhjbHVkaW5nIGJyb2tpbmcgMjAxNS4JSlVOMDkwMzA5F0hvdXNpbmcgU29sdXRpb25zIEdyb3VwABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAhAPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyODQRQmFua2luZyBTZXJ2aWNlcy4RQmFua2luZyBTZXJ2aWNlcy4JSlVOMDkwMjg0F1N0cm91ZCBEaXN0cmljdCBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAhEPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMDdCUDIwNDQzIERSRCDigJQgUHJvdmlzaW9uIG9mIExHViBEcml2ZXJzIGZvciBXaW50ZXIgU2VydmljZSBEdXRpZXMuQlAyMDQ0MyBEUkQg4oCUIFByb3Zpc2lvbiBvZiBMR1YgRHJpdmVycyBmb3IgV2ludGVyIFNlcnZpY2UgRHV0aWVzLglKVU4wOTAzMDciRGVwYXJ0bWVudCBvZiBSZWdpb25hbCBEZXZlbG9wbWVudAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAISD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMzA1RUhRSVAgTkNBIDE2MyBOYXRpb25hbCBMZWFybmluZyBEaXNhYmlsaXR5IE1vcnRhbGl0eSBSZXZpZXcgUHJvZ3JhbW1lLkVIUUlQIE5DQSAxNjMgTmF0aW9uYWwgTGVhcm5pbmcgRGlzYWJpbGl0eSBNb3J0YWxpdHkgUmV2aWV3IFByb2dyYW1tZS4JSlVOMDkwMzA1KkhlYWx0aGNhcmUgUXVhbGl0eSBJbXByb3ZlbWVudCBQYXJ0bmVyc2hpcAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAITD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMzA2NVN1cHBseSBvZiBQYXRob2xvZ3kg4oCYU2VuZCBhd2F54oCZIHRlc3Rpbmcgc2VydmljZXMuNVN1cHBseSBvZiBQYXRob2xvZ3kg4oCYU2VuZCBhd2F54oCZIHRlc3Rpbmcgc2VydmljZXMuCUpVTjA5MDMwNi1XZXN0ZXJuIFN1c3NleCBIb3NwaXRhbHMgTkhTIEZvdW5kYXRpb24gVHJ1c3QAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCFA9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI4MyZQcm92aXNpb24gb2YgQ2FzaCBDb2xsZWN0aW9uIFNlcnZpY2VzLiZQcm92aXNpb24gb2YgQ2FzaCBDb2xsZWN0aW9uIFNlcnZpY2VzLglKVU4wOTAyODMkTm9ydGggSGVydGZvcmRzaGlyZSBEaXN0cmljdCBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAhUPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyODIYV2FzdGUgSGF1bGFnZSBGcmFtZXdvcmsuGFdhc3RlIEhhdWxhZ2UgRnJhbWV3b3JrLglKVU4wOTAyODIkUmVkY2FyIGFuZCBDbGV2ZWxhbmQgQm9yb3VnaCBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAhYPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMDRFUHJvdmlzaW9uIG9mIEFyY2hpdGVjdHVyYWwgU2VydmljZXMgZm9yIHRoZSBCZWxwZXIgSW50ZWdyYXRlZCBTY2hlbWUuRVByb3Zpc2lvbiBvZiBBcmNoaXRlY3R1cmFsIFNlcnZpY2VzIGZvciB0aGUgQmVscGVyIEludGVncmF0ZWQgU2NoZW1lLglKVU4wOTAzMDQZRGVyYnlzaGlyZSBDb3VudHkgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIXD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMzAzNENsZWFuaW5nIFNlcnZpY2VzIOKAlCBTdHVkZW50IFJlc2lkZW5jZXMgRGVlcCBDbGVhbi40Q2xlYW5pbmcgU2VydmljZXMg4oCUIFN0dWRlbnQgUmVzaWRlbmNlcyBEZWVwIENsZWFuLglKVU4wOTAzMDMhVW5pdmVyc2l0eSBvZiB0aGUgV2VzdCBvZiBFbmdsYW5kABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAhgPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyODBITmV3IEJpb21lZGljYWwgUmVzZWFyY2ggQnVpbGRpbmcgUHJvamVjdCBNYW5hZ2VtZW50IENvbnN1bHRhbnQgU2VydmljZXMuSE5ldyBCaW9tZWRpY2FsIFJlc2VhcmNoIEJ1aWxkaW5nIFByb2plY3QgTWFuYWdlbWVudCBDb25zdWx0YW50IFNlcnZpY2VzLglKVU4wOTAyODAcVGhlIFVuaXZlcnNpdHkgb2YgTWFuY2hlc3RlcgAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIZD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjgxN0JXUEMgUkE3IOKAlCBQcm92aXNpb24gb2YgVmVoaWNsZSBIaXJlIGFuZCBNYWludGVuYW5jZS43QldQQyBSQTcg4oCUIFByb3Zpc2lvbiBvZiBWZWhpY2xlIEhpcmUgYW5kIE1haW50ZW5hbmNlLglKVU4wOTAyODEsQnJpc3RvbCBhbmQgV2VzdG9uIE5IUyBQdXJjaGFzaW5nIENvbnNvcnRpdW0AFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCGg9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDMwMmRUaGUgUHJvdmlzaW9uIG9mIEJ1aWxkaW5nIE1hbmFnZW1lbnQgU3lzdGVtcyAoQk1TKSwgSW50ZWdyYXRlZCBTZXJ2aWNlcyBhbmQgUmVsYXRlZCBDb250cm9scyBNYWludGVuZFRoZSBQcm92aXNpb24gb2YgQnVpbGRpbmcgTWFuYWdlbWVudCBTeXN0ZW1zIChCTVMpLCBJbnRlZ3JhdGVkIFNlcnZpY2VzIGFuZCBSZWxhdGVkIENvbnRyb2xzIE1haW50ZW4JSlVOMDkwMzAyGVVuaXZlcnNpdHkgQ29sbGVnZSBMb25kb24AFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCGw9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI3OSZDYXJlcnMgSW5mb3JtYXRpb24gYW5kIEFkdmljZSBTZXJ2aWNlLiZDYXJlcnMgSW5mb3JtYXRpb24gYW5kIEFkdmljZSBTZXJ2aWNlLglKVU4wOTAyNzkeTm90dGluZ2hhbXNoaXJlIENvdW50eSBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAhwPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMDFMVGhlIFByb3Zpc2lvbiBvZiBTY2hvb2wgYW5kIExvY2FsIFRyYW5zcG9ydCBTZXJ2aWNlcywgTG9ybiDigJQgMTMxMU0sIDEzMjZSLkxUaGUgUHJvdmlzaW9uIG9mIFNjaG9vbCBhbmQgTG9jYWwgVHJhbnNwb3J0IFNlcnZpY2VzLCBMb3JuIOKAlCAxMzExTSwgMTMyNlIuCUpVTjA5MDMwMRdBcmd5bGwgYW5kIEJ1dGUgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIdD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjc4NU1lZGlhIE1vbml0b3JpbmcgYW5kIEV2YWx1YXRpb24gYW5kIFJlbGF0ZWQgU2VydmljZXMuNU1lZGlhIE1vbml0b3JpbmcgYW5kIEV2YWx1YXRpb24gYW5kIFJlbGF0ZWQgU2VydmljZXMuCUpVTjA5MDI3OEtUaGUgTWluaXN0ZXIgZm9yIHRoZSBDYWJpbmV0IE9mZmljZSBhY3RpbmcgdGhyb3VnaCBDcm93biBDb21tZXJjaWFsIFNlcnZpY2UAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCHg9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI3NyhQaGFybWFjeSBPdXRwYXRpZW50IERpc3BlbnNpbmcgU2VydmljZXMuKFBoYXJtYWN5IE91dHBhdGllbnQgRGlzcGVuc2luZyBTZXJ2aWNlcy4JSlVOMDkwMjc3Jk5vcnRoYW1wdG9uIEdlbmVyYWwgSG9zcGl0YWwgTkhTIFRydXN0ABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAh8PZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAzMDBPVDgwOCBMb2NhbCBTZXJ2aWNlIFRyYW5zcG9ydCBQcm92aXNpb24gZm9yIEJ1cnRvbiDigJQgU3RvbmUgYW5kIE1vb3JsYW5kcyBBcmVhLk9UODA4IExvY2FsIFNlcnZpY2UgVHJhbnNwb3J0IFByb3Zpc2lvbiBmb3IgQnVydG9uIOKAlCBTdG9uZSBhbmQgTW9vcmxhbmRzIEFyZWEuCUpVTjA5MDMwMCdUcmFuc3BvcnQgYW5kIFRoZSBDb25uZWN0ZWQgQ291bnR5IFVuaXQAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCIA9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI5OShMaWJyYXJ5IFJlc291cmNlIExpc3QgTWFuYWdlbWVudCBTeXN0ZW0uKExpYnJhcnkgUmVzb3VyY2UgTGlzdCBNYW5hZ2VtZW50IFN5c3RlbS4JSlVOMDkwMjk5GFVuaXZlcnNpdHkgb2YgQmlybWluZ2hhbQAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIhD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjc2KFNwZWNpYWxpc3QgR3JvdW5kcyBNYWludGVuYW5jZSBTZXJ2aWNlcy4oU3BlY2lhbGlzdCBHcm91bmRzIE1haW50ZW5hbmNlIFNlcnZpY2VzLglKVU4wOTAyNzYaVGFuZHJpZGdlIERpc3RyaWN0IENvdW5jaWwAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCIg9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI3NVxQcm92aXNpb24gT2YgQWlyIFNlcnZpY2VzIEJldHdlZW4gT2JhbiBNYWlubGFuZCBBbmQgVGhlIElzbGFuZHMgT2YgQ29sbCwgQ29sb25zYXkgQW5kIFRpcmVlLlxQcm92aXNpb24gT2YgQWlyIFNlcnZpY2VzIEJldHdlZW4gT2JhbiBNYWlubGFuZCBBbmQgVGhlIElzbGFuZHMgT2YgQ29sbCwgQ29sb25zYXkgQW5kIFRpcmVlLglKVU4wOTAyNzUXQXJneWxsIGFuZCBCdXRlIENvdW5jaWwAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCIw9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI5NzhBcmNoaXRlY3R1cmFsIFNlcnZpY2VzIGZvciBOZXcgQnVpbGQgQWZmb3JkYWJsZSBIb3VzaW5nLjhBcmNoaXRlY3R1cmFsIFNlcnZpY2VzIGZvciBOZXcgQnVpbGQgQWZmb3JkYWJsZSBIb3VzaW5nLglKVU4wOTAyOTcYV2VhbGRlbiBEaXN0cmljdCBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAiQPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyOTguV1NDQyBESiDigJQgQ291bnRyeXNpZGUgQ29udHJhY3RvcnMgRnJhbWV3b3JrLi5XU0NDIERKIOKAlCBDb3VudHJ5c2lkZSBDb250cmFjdG9ycyBGcmFtZXdvcmsuCUpVTjA5MDI5OBpXZXN0IFN1c3NleCBDb3VudHkgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIlD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjk2NU1hY2tpbnRvc2ggUmVzdG9yYXRpb24gUHJvamVjdCDigJQgUXVhbnRpdHkgU3VydmV5b3IuNU1hY2tpbnRvc2ggUmVzdG9yYXRpb24gUHJvamVjdCDigJQgUXVhbnRpdHkgU3VydmV5b3IuCUpVTjA5MDI5NhVHbGFzZ293IFNjaG9vbCBvZiBBcnQAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCJg9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI5NR9QZXJzb25hbCBTdXBwb3J0IGluIEV4dHJhIENhcmUuH1BlcnNvbmFsIFN1cHBvcnQgaW4gRXh0cmEgQ2FyZS4JSlVOMDkwMjk1IVRoZSBCb3JvdWdoIENvdW5jaWwgb2YgQ2FsZGVyZGFsZQAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAInD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjc0MFByb3Zpc2lvbiBvZiBMYXVuZHJ5IFNlcnZpY2VzIGZvciBOb3JzZUNhcmUgTHRkLjBQcm92aXNpb24gb2YgTGF1bmRyeSBTZXJ2aWNlcyBmb3IgTm9yc2VDYXJlIEx0ZC4JSlVOMDkwMjc0C05vcnNlIEdyb3VwABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAigPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyOTQlRWxlY3Ryb25pYyBQYXltZW50IFNlcnZpY2VzIOKAlCAyMDE1LiVFbGVjdHJvbmljIFBheW1lbnQgU2VydmljZXMg4oCUIDIwMTUuCUpVTjA5MDI5NB9Ob3J0aGVybiBIb3VzaW5nIENvbnNvcnRpdW0gTHRkABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAikPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyNzNNUGFya2luZyBhbmQgQnVzIExhbmUgRW5mb3JjZW1lbnQgYW5kIFBlcm1pdCBNYW5hZ2VtZW50IFNvZnR3YXJlIGFuZCBIYXJkd2FyZS5NUGFya2luZyBhbmQgQnVzIExhbmUgRW5mb3JjZW1lbnQgYW5kIFBlcm1pdCBNYW5hZ2VtZW50IFNvZnR3YXJlIGFuZCBIYXJkd2FyZS4JSlVOMDkwMjczEkxlZWRzIENpdHkgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIqD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjkyI1Nob3J0IEJyZWFrcyBmb3IgRGlzYWJsZWQgQ2hpbGRyZW4uI1Nob3J0IEJyZWFrcyBmb3IgRGlzYWJsZWQgQ2hpbGRyZW4uCUpVTjA5MDI5MhRCcmlzdG9sIENpdHkgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIrD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjkzLURTRCDigJQgUHJvdmlzaW9uIG9mIENMQVMgYW5kIENoZWNrIFNlcnZpY2VzLi1EU0Qg4oCUIFByb3Zpc2lvbiBvZiBDTEFTIGFuZCBDaGVjayBTZXJ2aWNlcy4JSlVOMDkwMjkzIURlcGFydG1lbnQgZm9yIFNvY2lhbCBEZXZlbG9wbWVudAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIsD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjkxLUdXNDgwOSB8IERldmVsb3BpbmcgQ29uc3VsdGFuY3kgU2tpbGxzIHwgRFdQLi1HVzQ4MDkgfCBEZXZlbG9waW5nIENvbnN1bHRhbmN5IFNraWxscyB8IERXUC4JSlVOMDkwMjkxGENhcGl0YSBCdXNpbmVzcyBTZXJ2aWNlcwAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAItD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjcyJlJlcGxhY2VtZW50IExpYnJhcnkgTWFuYWdlbWVudCBTeXN0ZW0uJlJlcGxhY2VtZW50IExpYnJhcnkgTWFuYWdlbWVudCBTeXN0ZW0uCUpVTjA5MDI3MhdTb21lcnNldCBDb3VudHkgQ291bmNpbAAVQ29udHJhY3QgQXdhcmQgTm90aWNlZAIuD2QWBGYPZBYCZg8VAgoyNy8wNi8yMDE1lwE8aW1nIHNyYz0iL2ltYWdlcy9ldXJvZmxhZy5naWYiIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMSIgYWx0PSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIHRpdGxlPSJOb3RpY2UgcHVibGlzaGVkIGluIEV1cm9wZWFuIEpvdXJuYWwiIC8+Jm5ic3A7ZAIBD2QWAmYPFQcqL3NlYXJjaC9zaG93L3NlYXJjaF92aWV3LmFzcHg/SUQ9SlVOMDkwMjcxO1Njb3R0aXNoIEJvcmRlcnMgU3VzdGFpbmFibGUgVHJhbnNwb3J0IEZyYW1ld29yayBBZ3JlZW1lbnQuO1Njb3R0aXNoIEJvcmRlcnMgU3VzdGFpbmFibGUgVHJhbnNwb3J0IEZyYW1ld29yayBBZ3JlZW1lbnQuCUpVTjA5MDI3MRhTY290dGlzaCBCb3JkZXJzIENvdW5jaWwAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCLw9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI2OTRBc2Jlc3RvcyBTdXJ2ZXlpbmcgU2FtcGxpbmcgYW5kIEFuYWx5dGljYWwgU2VydmljZXMuNEFzYmVzdG9zIFN1cnZleWluZyBTYW1wbGluZyBhbmQgQW5hbHl0aWNhbCBTZXJ2aWNlcy4JSlVOMDkwMjY5EVJpdmVyIENseWRlIEhvbWVzABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAjAPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyNzBAR1c0NzgxIHwgSFNFIExpZnRpbmcgYW5kIFNsaW5naW5nIHwgSGVhbHRoIGFuZCBTYWZldHkgRXhlY3V0aXZlLkBHVzQ3ODEgfCBIU0UgTGlmdGluZyBhbmQgU2xpbmdpbmcgfCBIZWFsdGggYW5kIFNhZmV0eSBFeGVjdXRpdmUuCUpVTjA5MDI3MBhDYXBpdGEgQnVzaW5lc3MgU2VydmljZXMAFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCMQ9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI5MFdQYXJ0aWNrIEhvdXNpbmcgQXNzb2NpYXRpb24gUGFzc2VuZ2VyIExpZnQgU2VydmljaW5nIGFuZCBSZWFjdGl2ZSBNYWludGVuYW5jZSBDb250cmFjdC5XUGFydGljayBIb3VzaW5nIEFzc29jaWF0aW9uIFBhc3NlbmdlciBMaWZ0IFNlcnZpY2luZyBhbmQgUmVhY3RpdmUgTWFpbnRlbmFuY2UgQ29udHJhY3QuCUpVTjA5MDI5MBtQYXJ0aWNrIEhvdXNpbmcgQXNzb2NpYXRpb24AFUNvbnRyYWN0IEF3YXJkIE5vdGljZWQCMg9kFgRmD2QWAmYPFQIKMjcvMDYvMjAxNZcBPGltZyBzcmM9Ii9pbWFnZXMvZXVyb2ZsYWcuZ2lmIiB3aWR0aD0iMTMiIGhlaWdodD0iMTEiIGFsdD0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiB0aXRsZT0iTm90aWNlIHB1Ymxpc2hlZCBpbiBFdXJvcGVhbiBKb3VybmFsIiAvPiZuYnNwO2QCAQ9kFgJmDxUHKi9zZWFyY2gvc2hvdy9zZWFyY2hfdmlldy5hc3B4P0lEPUpVTjA5MDI2N2RUZXJtIENvbnRyYWN0IGZvciBHYXMgU2VydmljaW5nLCBSZXNwb25zaXZlIFJlcGFpcnMgYW5kIGFzc29jaWF0ZWQgd29ya3MgdG8gc3lzdGVtcyBhbmQgYXBwbGlhbmNlcy9lZFRlcm0gQ29udHJhY3QgZm9yIEdhcyBTZXJ2aWNpbmcsIFJlc3BvbnNpdmUgUmVwYWlycyBhbmQgYXNzb2NpYXRlZCB3b3JrcyB0byBzeXN0ZW1zIGFuZCBhcHBsaWFuY2VzL2UJSlVOMDkwMjY3HUFyaGFnIEhvdXNpbmcgQXNzb2NpYXRpb24gTHRkABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAjMPZBYEZg9kFgJmDxUCCjI3LzA2LzIwMTWXATxpbWcgc3JjPSIvaW1hZ2VzL2V1cm9mbGFnLmdpZiIgd2lkdGg9IjEzIiBoZWlnaHQ9IjExIiBhbHQ9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgdGl0bGU9Ik5vdGljZSBwdWJsaXNoZWQgaW4gRXVyb3BlYW4gSm91cm5hbCIgLz4mbmJzcDtkAgEPZBYCZg8VByovc2VhcmNoL3Nob3cvc2VhcmNoX3ZpZXcuYXNweD9JRD1KVU4wOTAyNDk8UHJvdmlzaW9uIG9mIEZpcmUgRmlnaHRpbmcgRXF1aXBtZW50IE1haW50ZW5hbmNlIGFuZCBSZXBhaXIuPFByb3Zpc2lvbiBvZiBGaXJlIEZpZ2h0aW5nIEVxdWlwbWVudCBNYWludGVuYW5jZSBhbmQgUmVwYWlyLglKVU4wOTAyNDkVQWJlcmRlZW5zaGlyZSBDb3VuY2lsABVDb250cmFjdCBBd2FyZCBOb3RpY2VkAjQPDxYCHwVoZGQCCQ9kFgICAQ9kFgYCAQ8PFgIfAgUDMjU1ZGQCBQ8QZBAVBgExATIBMwE0ATUBNhUGATEBMgEzATQBNQE2FCsDBmdnZ2dnZ2RkAgcPDxYCHwIFATZkZAINDw8WBh4KU2VhcmNoVGV4dAUTU2VhcmNoIGZvciBjYXRlZ29yeR4ORGVzdGluYXRpb25VUkwFGVNlYXJjaF9DYXRlZ29yeV9MaXN0LmFzcHgeCVJlc3VsdFVSTAU4aHR0cDovL3d3dy5zZWxsMndhbGVzLmdvdi51ay9TZWFyY2gvU2VhcmNoX0NhdGVnb3J5LmFzcHhkFgICAw8PZBYCHgdvbmZvY3VzBTRpZih0aGlzLnZhbHVlPT0nU2VhcmNoIGZvciBjYXRlZ29yeScpIHRoaXMudmFsdWU9Jyc7ZAIPDxYCHwkCEBYgZg9kFgJmDxUDAzEwMBRBZ3JpY3VsdHVyZSBhbmQgRm9vZBRBZ3JpY3VsdHVyZSBhbmQgRm9vZGQCAQ9kFgJmDxUDAzExMB1Db21wdXRlciBhbmQgUmVsYXRlZCBTZXJ2aWNlcx1Db21wdXRlciBhbmQgUmVsYXRlZCBTZXJ2aWNlc2QCAg9kFgJmDxUDAzEyMBxDb25zdHJ1Y3Rpb24gYW5kIFJlYWwgRXN0YXRlHENvbnN0cnVjdGlvbiBhbmQgUmVhbCBFc3RhdGVkAgMPZBYCZg8VAwMxMzAURGVmZW5jZSBhbmQgc2VjdXJpdHkURGVmZW5jZSBhbmQgc2VjdXJpdHlkAgQPZBYCZg8VAwMxNDAJRWR1Y2F0aW9uCUVkdWNhdGlvbmQCBQ9kFgJmDxUDAzE1MBtFbmVyZ3kgYW5kIFJlbGF0ZWQgU2VydmljZXMbRW5lcmd5IGFuZCBSZWxhdGVkIFNlcnZpY2VzZAIGD2QWAmYPFQMDMTYwGkVudmlyb25tZW50IGFuZCBTYW5pdGF0aW9uGkVudmlyb25tZW50IGFuZCBTYW5pdGF0aW9uZAIHD2QWAmYPFQMDMTcwHEZpbmFuY2UgYW5kIFJlbGF0ZWQgU2VydmljZXMcRmluYW5jZSBhbmQgUmVsYXRlZCBTZXJ2aWNlc2QCCA9kFgJmDxUDAzE4MBZNYXRlcmlhbHMgYW5kIFByb2R1Y3RzFk1hdGVyaWFscyBhbmQgUHJvZHVjdHNkAgkPZBYCZg8VAwMxOTAPTWluaW5nIGFuZCBPcmVzD01pbmluZyBhbmQgT3Jlc2QCCg9kFgJmDxUDAzIwMA5PdGhlciBTZXJ2aWNlcw5PdGhlciBTZXJ2aWNlc2QCCw9kFgJmDxUDAzIxMBdQcmludGluZyBhbmQgUHVibGlzaGluZxdQcmludGluZyBhbmQgUHVibGlzaGluZ2QCDA9kFgJmDxUDAzIyMBhSZXNlYXJjaCBhbmQgRGV2ZWxvcG1lbnQYUmVzZWFyY2ggYW5kIERldmVsb3BtZW50ZAIND2QWAmYPFQMCMjMTU2VsbDJXYWxlcyBQcm9qZWN0cxNTZWxsMldhbGVzIFByb2plY3RzZAIOD2QWAmYPFQMDMjMwGFRlY2hub2xvZ3kgYW5kIEVxdWlwbWVudBhUZWNobm9sb2d5IGFuZCBFcXVpcG1lbnRkAg8PZBYCZg8VAwMyNDAeVHJhbnNwb3J0IGFuZCBSZWxhdGVkIFNlcnZpY2VzHlRyYW5zcG9ydCBhbmQgUmVsYXRlZCBTZXJ2aWNlc2QCEQ8PFgIfAgUEMjAxNWRkGAIFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYIBSpjdGwwMCRDb250ZW50UGxhY2VIb2xkZXIxJE5hdkJhcjEkY21kRmlyc3QFKWN0bDAwJENvbnRlbnRQbGFjZUhvbGRlcjEkTmF2QmFyMSRjbWRQcmV2BSljdGwwMCRDb250ZW50UGxhY2VIb2xkZXIxJE5hdkJhcjEkY21kTmV4dAUpY3RsMDAkQ29udGVudFBsYWNlSG9sZGVyMSROYXZCYXIxJGNtZExhc3QFKmN0bDAwJENvbnRlbnRQbGFjZUhvbGRlcjEkTmF2QmFyMiRjbWRGaXJzdAUpY3RsMDAkQ29udGVudFBsYWNlSG9sZGVyMSROYXZCYXIyJGNtZFByZXYFKWN0bDAwJENvbnRlbnRQbGFjZUhvbGRlcjEkTmF2QmFyMiRjbWROZXh0BSljdGwwMCRDb250ZW50UGxhY2VIb2xkZXIxJE5hdkJhcjIkY21kTGFzdAUkY3RsMDAkQ29udGVudFBsYWNlSG9sZGVyMSRncmRSZXN1bHRzDzwrAAwBCAIGZH1jS8guaFVh6vt5ju9w+MHLff4QjrrH/IkdsMh5rSqn" />


<script src="/ScriptResource.axd?d=6pGwe9czpNl-RbQRvnakyXcZpnoVvUh4iHjRyePJlyz8TOCbZeeEgU3E62SymxkO98K4UzBz3rERIOItjeEacKwk1z5QJB1Zrd6MLNKeVQIBLeJzd7UdsFBx4vgobH_EX8REjosbfRQKZ1anHn6Dlqnn4Fq4m2kT1yrQhvMGPBfC4gH92tiaHQblEe2SApIT0&amp;t=7b689585" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
if (typeof(Sys) === 'undefined') throw new Error('ASP.NET Ajax client-side framework failed to load.');
//]]>
</script>

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="CAB88159" />
<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdABocTz6M9+0syqYQQbAYx4dQ+LoAa7I07YxwCTkEj7KCRtQIBLQUCt+6biExuwCxfrCc7Ow4XAEAHaEvYGrECkBPq0x8b1TpeKY5MewoTkROHdHaDfUMiMdI35ekbTMaqOt3/nGVMiE1fJ/2hK2ILzlNuan1tZzwkcdRqRox3w2ZKmKXveC30QJvSkNhXv0SZJJi0RAbou94nKoTVtzttmsfjFslEwyhmp9/aq/FgFIIEmWPjcWw7C4MP3Gii6UpOjz2jYp0NwelRoQhtZOr6OGbI5fEqKNETLA36d2jIoRPZpr5yIMaVQHjsro2fw0vHVds7HrZPLiaHLPtV2pbkU1KWD3VVFQfeYbdxWFDQnhCtXnvPru14uglfBqOokKxoJQ9RP65LoSI/NWFw/VO+O/hK9bUkKxIA+1DHJHsP+oO8DxmzPpIcdDKRow6eojrPOH3UgQqs2JtP2BybO89q5IPMtXS73VmCA0ObDOKWX3polBgQPGR211fCtSIy6a7pqtkN3TIgZR3rOLzglo60z28auQdXjQhHduiOjbsgld1ePL1djrZFY9hD9G+JYKpuOx2YK+QpNCqERWA6pL7cLIi" />
    
    <div id="Wrapper">
        


        <div id="ctl00_CookieBar_pnlCookie" class="CookieBar">
	
    <span class="CookieText"><strong>This site uses cookies. By continuing to browse the site you are agreeing to
        our use of cookies. <a href="../sitehelp/help_privacy.aspx" title="Privacy Policy &amp; Cookies">
            Read our Privacy Policy</a>.</strong></span> 
                <span style="float:right"><strong><a id="ctl00_CookieBar_lnkCookies" title="Accept our use of cookies" class="cookieAccept" href="javascript:__doPostBack(&#39;ctl00$CookieBar$lnkCookies&#39;,&#39;&#39;)">Accept Cookies</a></strong></span>
    <div style="clear:both;"></div>

</div>

        <div id="Header">
            <div id="MainMenu">
                    <a href="#Content" class="Skip">Skip to content</a>
                <ul class="Horizontal">
                    <li><a href="/AboutUs/aboutus_main.aspx">About Us</a></li>
                        <li><a href="/Table_of_Contents.aspx" accesskey="3">Site Map</a></li>
                    <li><a href="/AboutUs/aboutus_contactus.aspx" accesskey="9">Contact Us</a></li>
                    <li>
                            <a id="ctl00_lnkLogin" title="Log in" class="Login" href="/Access/Login.aspx">Log in</a>
                        </li>
                        <li><a id="ctl00_lnkCymraeg" href="http://www.gwerthwchigymru.gov.uk/">Cymraeg</a></li>
                </ul>
            </div>
                <div id="HeaderContent">
                    <div style="width:67%; margin-bottom:1em; float:left">
                        <div class="Logo">
                            <a href="/Default.aspx" accesskey="1">
                                <img src="/Images/Logo.png" alt="sell2wales Home" /></a>
                        </div>
                        <div class="Logo">
                            <img src="/Images/Welsh_Government.png" alt="Welsh Government" />
                        </div>
                        <span>Website Helpline:
                             0844 561 0672</span>
                    </div>
            <div id="Strapline">
                        <div id="HelplineInfo">
                            Our helpline is open from 9.00am to 5.00pm, Monday to Friday, other than on bank and public holidays.
                        </div>
                    </div>
                </div>
            </div>
            <div id="SubMenu">
                <ul class="Horizontal">
                    <li><a href="/Default.aspx" title="Home">Home</a></li>
                    <li><a href="/Search/search_mainpage.aspx" accesskey="4">Browse Notices</a></li>
                    <li><a href="/Search/search_Auth.aspx">Search for Buyers</a></li>
                    <li><a href="/Membership/Member_ControlPanel.aspx">Suppliers</a></li>
                    <li><a href="/Authority/Authority_ControlPanel.aspx">Buyers</a></li>
                    <li><a href="/info/InfoCentre.aspx?ID=81">Info Centre</a></li>
                    <li><a href="/info/InfoCentre.aspx?ID=141">News &amp; Events</a></li>
                    <li><a href="/info/InfoCentre.aspx?ID=145" accesskey="6">Help &amp; Support</a></li>
                </ul>
        </div>
        <div id="Content">
            
    <h1>Notice Search</h1>
    <div id="BreadCrumb">
        <ul class="Horizontal">
            <li><span>You are here:</span>&nbsp;</li>
            <li><a href="/Default.aspx" title="Return to the home page">Home</a>&nbsp;&gt;&nbsp;</li>
            <li>Notice Search</li>
        </ul>
    </div>
    <p>Please select a notice title from the <em>Recently Published Notices</em> list to
        view the full notice, select a more advanced search option from the <em>Further Search
            Options</em> list, or use the <em>Notice Categories</em> list to find other
        notices which are of interest to you. For an explanation of the icons used in the
        Date column please visit the <a href="/sitehelp/help_icons.aspx" title="View an explanation of the icons used on this page">Icons Explained</a> page.
    </p>
    
        <p>View <a href="search_subcontracts.aspx" title="View Sub-Contract Notices">Sub-Contract
                Notices</a> only.</p>
    

        

    <div style="width: 100%; overflow: hidden; margin-top: 2em">
        <div style="float: left; width: 67%">
            <h2>Recently Published Notices</h2>

            
<section class="NavBar">
    <div class="Primary">
        <span id="ctl00_ContentPlaceHolder1_NavBar1_lblNumRecs">255</span>
        records found.&nbsp;
        <label for="ctl00_ContentPlaceHolder1_NavBar1_drpPageNo">Jump to page</label>
        <select name="ctl00$ContentPlaceHolder1$NavBar1$drpPageNo" id="ctl00_ContentPlaceHolder1_NavBar1_drpPageNo">
	<option selected="selected" value="1">1</option>
	<option value="2">2</option>
	<option value="3">3</option>
	<option value="4">4</option>
	<option value="5">5</option>
	<option value="6">6</option>

</select>
        of
        <span id="ctl00_ContentPlaceHolder1_NavBar1_lblNumPages">6</span><input type="submit" name="ctl00$ContentPlaceHolder1$NavBar1$btnGo" value="Go" id="ctl00_ContentPlaceHolder1_NavBar1_btnGo" title="Go to the selected page" class="Button" />
    </div>
    <div class="Secondary">
        <ul>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar1$cmdFirst" id="ctl00_ContentPlaceHolder1_NavBar1_cmdFirst" title="Go to the first page of results" src="../Images/movefirst.gif" alt="Go to the first page of results" /></li>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar1$cmdPrev" id="ctl00_ContentPlaceHolder1_NavBar1_cmdPrev" title="Go back to the previous page of results" src="../Images/moveprev.gif" alt="Go back to the previous page of results" /></li>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar1$cmdNext" id="ctl00_ContentPlaceHolder1_NavBar1_cmdNext" title="Go to the next page of results" src="../Images/MoveNext.gif" alt="Go to the next page of results" /></li>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar1$cmdLast" id="ctl00_ContentPlaceHolder1_NavBar1_cmdLast" title="Go to the last page of results" src="../Images/movelast.gif" alt="Go to the last page of results" /></li>
        </ul>
    </div>
</section>

            <div>
	<table class="Grid" cellspacing="0" cellpadding="2" summary="Recently published contract notices, sorted by the date they were published" id="ctl00_ContentPlaceHolder1_grdResults" width="100%">
		<tr class="GridHeader">
			<th scope="col" width="80">Date</th><th scope="col">Notice Details</th>
		</tr><tr class="GridItem" style="display:none;">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=SEP006883'
                                title="Notice Title - Musculoskeletal.">
                                Musculoskeletal.</a><br />
                            Reference No:&nbsp;SEP006883<br />
                            Published By:&nbsp;NHS Darlington Clinical Commissioning Group (CCG)<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Prior Information Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090332'
                                title="Notice Title - Supply, deliver, erect, test and commission of Rubber Tyred Gantry Cranes (RTGs).">
                                Supply, deliver, erect, test and commission of Rubber Tyred Gantry Cranes (RTGs).</a><br />
                            Reference No:&nbsp;JUN090332<br />
                            Published By:&nbsp;PD Teesport Limited<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090333'
                                title="Notice Title - Railway websites for The Go-Ahead Group.">
                                Railway websites for The Go-Ahead Group.</a><br />
                            Reference No:&nbsp;JUN090333<br />
                            Published By:&nbsp;Go Ahead Group Holding<br />
                            Deadline Date:&nbsp;03-Jul-15<br />
                            Notice Type:&nbsp;Contract Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090334'
                                title="Notice Title - The provision of a Loss Adjuster to service the whole of the Anglian Water region, for mainly public">
                                The provision of a Loss Adjuster to service the whole of the Anglian Water region, for mainly public</a><br />
                            Reference No:&nbsp;JUN090334<br />
                            Published By:&nbsp;Anglian Water Services Limited<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090331'
                                title="Notice Title - NRHS-2014-TBC Grinding.">
                                NRHS-2014-TBC Grinding.</a><br />
                            Reference No:&nbsp;JUN090331<br />
                            Published By:&nbsp;Network Rail High Speed<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090311'
                                title="Notice Title - KPL-10MW Energy Storage Facility — Lot 2 Inverter Equipment.">
                                KPL-10MW Energy Storage Facility — Lot 2 Inverter Equipment.</a><br />
                            Reference No:&nbsp;JUN090311<br />
                            Published By:&nbsp;AES Kilroot Power Ltd<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090289'
                                title="Notice Title - Inbound Mail Contract.">
                                Inbound Mail Contract.</a><br />
                            Reference No:&nbsp;JUN090289<br />
                            Published By:&nbsp;North Hertfordshire District Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090330'
                                title="Notice Title - Provision of an Integrated Community Adult Drug and Alcohol Recovery and Treatment Service.">
                                Provision of an Integrated Community Adult Drug and Alcohol Recovery and Treatment Service.</a><br />
                            Reference No:&nbsp;JUN090330<br />
                            Published By:&nbsp;Gloucestershire County Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090310'
                                title="Notice Title - Dynamic Purchasing System for Local and Home to School Transport — Further Competition.">
                                Dynamic Purchasing System for Local and Home to School Transport — Further Competition.</a><br />
                            Reference No:&nbsp;JUN090310<br />
                            Published By:&nbsp;North Lincolnshire Borough Council<br />
                            Deadline Date:&nbsp;09-Jul-15<br />
                            Notice Type:&nbsp;Contract Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090288'
                                title="Notice Title - Purchase an e-Social Care Purchasing System for Adult Social Care.">
                                Purchase an e-Social Care Purchasing System for Adult Social Care.</a><br />
                            Reference No:&nbsp;JUN090288<br />
                            Published By:&nbsp;Isle of Wight Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090287'
                                title="Notice Title - Multiple Framework Agreement for Transport Planning, Modelling and Audit Services 2011-2014.">
                                Multiple Framework Agreement for Transport Planning, Modelling and Audit Services 2011-2014.</a><br />
                            Reference No:&nbsp;JUN090287<br />
                            Published By:&nbsp;Transport Scotland<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090286'
                                title="Notice Title - SWCSU — Somerset CCG-NHS 111 and Primary Care Out of Hours services in two LOTS.">
                                SWCSU — Somerset CCG-NHS 111 and Primary Care Out of Hours services in two LOTS.</a><br />
                            Reference No:&nbsp;JUN090286<br />
                            Published By:&nbsp;NHS Somerset Clinical Commissioning Group<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090285'
                                title="Notice Title - Provision of Local Bus Services.">
                                Provision of Local Bus Services.</a><br />
                            Reference No:&nbsp;JUN090285<br />
                            Published By:&nbsp;South Yorkshire Passenger Transport Executive<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090308'
                                title="Notice Title - Humber University Technical College Leadership and Improvement Services.">
                                Humber University Technical College Leadership and Improvement Services.</a><br />
                            Reference No:&nbsp;JUN090308<br />
                            Published By:&nbsp;Humber UTC<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090309'
                                title="Notice Title - Provision of Non Life Insurance Services excluding broking 2015.">
                                Provision of Non Life Insurance Services excluding broking 2015.</a><br />
                            Reference No:&nbsp;JUN090309<br />
                            Published By:&nbsp;Housing Solutions Group<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090284'
                                title="Notice Title - Banking Services.">
                                Banking Services.</a><br />
                            Reference No:&nbsp;JUN090284<br />
                            Published By:&nbsp;Stroud District Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090307'
                                title="Notice Title - P20443 DRD — Provision of LGV Drivers for Winter Service Duties.">
                                P20443 DRD — Provision of LGV Drivers for Winter Service Duties.</a><br />
                            Reference No:&nbsp;JUN090307<br />
                            Published By:&nbsp;Department of Regional Development<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090305'
                                title="Notice Title - HQIP NCA 163 National Learning Disability Mortality Review Programme.">
                                HQIP NCA 163 National Learning Disability Mortality Review Programme.</a><br />
                            Reference No:&nbsp;JUN090305<br />
                            Published By:&nbsp;Healthcare Quality Improvement Partnership<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090306'
                                title="Notice Title - Supply of Pathology ‘Send away’ testing services.">
                                Supply of Pathology ‘Send away’ testing services.</a><br />
                            Reference No:&nbsp;JUN090306<br />
                            Published By:&nbsp;Western Sussex Hospitals NHS Foundation Trust<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090283'
                                title="Notice Title - Provision of Cash Collection Services.">
                                Provision of Cash Collection Services.</a><br />
                            Reference No:&nbsp;JUN090283<br />
                            Published By:&nbsp;North Hertfordshire District Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090282'
                                title="Notice Title - Waste Haulage Framework.">
                                Waste Haulage Framework.</a><br />
                            Reference No:&nbsp;JUN090282<br />
                            Published By:&nbsp;Redcar and Cleveland Borough Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090304'
                                title="Notice Title - Provision of Architectural Services for the Belper Integrated Scheme.">
                                Provision of Architectural Services for the Belper Integrated Scheme.</a><br />
                            Reference No:&nbsp;JUN090304<br />
                            Published By:&nbsp;Derbyshire County Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090303'
                                title="Notice Title - Cleaning Services — Student Residences Deep Clean.">
                                Cleaning Services — Student Residences Deep Clean.</a><br />
                            Reference No:&nbsp;JUN090303<br />
                            Published By:&nbsp;University of the West of England<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090280'
                                title="Notice Title - New Biomedical Research Building Project Management Consultant Services.">
                                New Biomedical Research Building Project Management Consultant Services.</a><br />
                            Reference No:&nbsp;JUN090280<br />
                            Published By:&nbsp;The University of Manchester<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090281'
                                title="Notice Title - BWPC RA7 — Provision of Vehicle Hire and Maintenance.">
                                BWPC RA7 — Provision of Vehicle Hire and Maintenance.</a><br />
                            Reference No:&nbsp;JUN090281<br />
                            Published By:&nbsp;Bristol and Weston NHS Purchasing Consortium<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090302'
                                title="Notice Title - The Provision of Building Management Systems (BMS), Integrated Services and Related Controls Mainten">
                                The Provision of Building Management Systems (BMS), Integrated Services and Related Controls Mainten</a><br />
                            Reference No:&nbsp;JUN090302<br />
                            Published By:&nbsp;University College London<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090279'
                                title="Notice Title - Carers Information and Advice Service.">
                                Carers Information and Advice Service.</a><br />
                            Reference No:&nbsp;JUN090279<br />
                            Published By:&nbsp;Nottinghamshire County Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090301'
                                title="Notice Title - The Provision of School and Local Transport Services, Lorn — 1311M, 1326R.">
                                The Provision of School and Local Transport Services, Lorn — 1311M, 1326R.</a><br />
                            Reference No:&nbsp;JUN090301<br />
                            Published By:&nbsp;Argyll and Bute Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090278'
                                title="Notice Title - Media Monitoring and Evaluation and Related Services.">
                                Media Monitoring and Evaluation and Related Services.</a><br />
                            Reference No:&nbsp;JUN090278<br />
                            Published By:&nbsp;The Minister for the Cabinet Office acting through Crown Commercial Service<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090277'
                                title="Notice Title - Pharmacy Outpatient Dispensing Services.">
                                Pharmacy Outpatient Dispensing Services.</a><br />
                            Reference No:&nbsp;JUN090277<br />
                            Published By:&nbsp;Northampton General Hospital NHS Trust<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090300'
                                title="Notice Title - T808 Local Service Transport Provision for Burton — Stone and Moorlands Area.">
                                T808 Local Service Transport Provision for Burton — Stone and Moorlands Area.</a><br />
                            Reference No:&nbsp;JUN090300<br />
                            Published By:&nbsp;Transport and The Connected County Unit<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090299'
                                title="Notice Title - Library Resource List Management System.">
                                Library Resource List Management System.</a><br />
                            Reference No:&nbsp;JUN090299<br />
                            Published By:&nbsp;University of Birmingham<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090276'
                                title="Notice Title - Specialist Grounds Maintenance Services.">
                                Specialist Grounds Maintenance Services.</a><br />
                            Reference No:&nbsp;JUN090276<br />
                            Published By:&nbsp;Tandridge District Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090275'
                                title="Notice Title - Provision Of Air Services Between Oban Mainland And The Islands Of Coll, Colonsay And Tiree.">
                                Provision Of Air Services Between Oban Mainland And The Islands Of Coll, Colonsay And Tiree.</a><br />
                            Reference No:&nbsp;JUN090275<br />
                            Published By:&nbsp;Argyll and Bute Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090297'
                                title="Notice Title - Architectural Services for New Build Affordable Housing.">
                                Architectural Services for New Build Affordable Housing.</a><br />
                            Reference No:&nbsp;JUN090297<br />
                            Published By:&nbsp;Wealden District Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090298'
                                title="Notice Title - WSCC DJ — Countryside Contractors Framework.">
                                WSCC DJ — Countryside Contractors Framework.</a><br />
                            Reference No:&nbsp;JUN090298<br />
                            Published By:&nbsp;West Sussex County Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090296'
                                title="Notice Title - Mackintosh Restoration Project — Quantity Surveyor.">
                                Mackintosh Restoration Project — Quantity Surveyor.</a><br />
                            Reference No:&nbsp;JUN090296<br />
                            Published By:&nbsp;Glasgow School of Art<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090295'
                                title="Notice Title - Personal Support in Extra Care.">
                                Personal Support in Extra Care.</a><br />
                            Reference No:&nbsp;JUN090295<br />
                            Published By:&nbsp;The Borough Council of Calderdale<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090274'
                                title="Notice Title - Provision of Laundry Services for NorseCare Ltd.">
                                Provision of Laundry Services for NorseCare Ltd.</a><br />
                            Reference No:&nbsp;JUN090274<br />
                            Published By:&nbsp;Norse Group<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090294'
                                title="Notice Title - Electronic Payment Services — 2015.">
                                Electronic Payment Services — 2015.</a><br />
                            Reference No:&nbsp;JUN090294<br />
                            Published By:&nbsp;Northern Housing Consortium Ltd<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090273'
                                title="Notice Title - Parking and Bus Lane Enforcement and Permit Management Software and Hardware.">
                                Parking and Bus Lane Enforcement and Permit Management Software and Hardware.</a><br />
                            Reference No:&nbsp;JUN090273<br />
                            Published By:&nbsp;Leeds City Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090292'
                                title="Notice Title - Short Breaks for Disabled Children.">
                                Short Breaks for Disabled Children.</a><br />
                            Reference No:&nbsp;JUN090292<br />
                            Published By:&nbsp;Bristol City Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090293'
                                title="Notice Title - DSD — Provision of CLAS and Check Services.">
                                DSD — Provision of CLAS and Check Services.</a><br />
                            Reference No:&nbsp;JUN090293<br />
                            Published By:&nbsp;Department for Social Development<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090291'
                                title="Notice Title - GW4809 | Developing Consultancy Skills | DWP.">
                                GW4809 | Developing Consultancy Skills | DWP.</a><br />
                            Reference No:&nbsp;JUN090291<br />
                            Published By:&nbsp;Capita Business Services<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090272'
                                title="Notice Title - Replacement Library Management System.">
                                Replacement Library Management System.</a><br />
                            Reference No:&nbsp;JUN090272<br />
                            Published By:&nbsp;Somerset County Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090271'
                                title="Notice Title - Scottish Borders Sustainable Transport Framework Agreement.">
                                Scottish Borders Sustainable Transport Framework Agreement.</a><br />
                            Reference No:&nbsp;JUN090271<br />
                            Published By:&nbsp;Scottish Borders Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090269'
                                title="Notice Title - Asbestos Surveying Sampling and Analytical Services.">
                                Asbestos Surveying Sampling and Analytical Services.</a><br />
                            Reference No:&nbsp;JUN090269<br />
                            Published By:&nbsp;River Clyde Homes<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090270'
                                title="Notice Title - GW4781 | HSE Lifting and Slinging | Health and Safety Executive.">
                                GW4781 | HSE Lifting and Slinging | Health and Safety Executive.</a><br />
                            Reference No:&nbsp;JUN090270<br />
                            Published By:&nbsp;Capita Business Services<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090290'
                                title="Notice Title - Partick Housing Association Passenger Lift Servicing and Reactive Maintenance Contract.">
                                Partick Housing Association Passenger Lift Servicing and Reactive Maintenance Contract.</a><br />
                            Reference No:&nbsp;JUN090290<br />
                            Published By:&nbsp;Partick Housing Association<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItemAlt">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090267'
                                title="Notice Title - Term Contract for Gas Servicing, Responsive Repairs and associated works to systems and appliances/e">
                                Term Contract for Gas Servicing, Responsive Repairs and associated works to systems and appliances/e</a><br />
                            Reference No:&nbsp;JUN090267<br />
                            Published By:&nbsp;Arhag Housing Association Ltd<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr><tr class="GridItem">
			<td>
                            27/06/2015
                            <img src="/images/euroflag.gif" width="13" height="11" alt="Notice published in European Journal" title="Notice published in European Journal" />&nbsp;
                        </td><td>
                            <a href='/search/show/search_view.aspx?ID=JUN090249'
                                title="Notice Title - Provision of Fire Fighting Equipment Maintenance and Repair.">
                                Provision of Fire Fighting Equipment Maintenance and Repair.</a><br />
                            Reference No:&nbsp;JUN090249<br />
                            Published By:&nbsp;Aberdeenshire Council<br />
                            Deadline Date:&nbsp;<br />
                            Notice Type:&nbsp;Contract Award Notice
                        </td>
		</tr>
	</table>
</div>
            <div id="ctl00_ContentPlaceHolder1_divNavBar2" class="GridItem">
                <!-- To add a top border to the div similar to the grid items above -->
                <br />
                
<section class="NavBar">
    <div class="Primary">
        <span id="ctl00_ContentPlaceHolder1_NavBar2_lblNumRecs">255</span>
        records found.&nbsp;
        <label for="ctl00_ContentPlaceHolder1_NavBar2_drpPageNo">Jump to page</label>
        <select name="ctl00$ContentPlaceHolder1$NavBar2$drpPageNo" id="ctl00_ContentPlaceHolder1_NavBar2_drpPageNo">
	<option selected="selected" value="1">1</option>
	<option value="2">2</option>
	<option value="3">3</option>
	<option value="4">4</option>
	<option value="5">5</option>
	<option value="6">6</option>

</select>
        of
        <span id="ctl00_ContentPlaceHolder1_NavBar2_lblNumPages">6</span><input type="submit" name="ctl00$ContentPlaceHolder1$NavBar2$btnGo" value="Go" id="ctl00_ContentPlaceHolder1_NavBar2_btnGo" title="Go to the selected page" class="Button" />
    </div>
    <div class="Secondary">
        <ul>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar2$cmdFirst" id="ctl00_ContentPlaceHolder1_NavBar2_cmdFirst" title="Go to the first page of results" src="../Images/movefirst.gif" alt="Go to the first page of results" /></li>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar2$cmdPrev" id="ctl00_ContentPlaceHolder1_NavBar2_cmdPrev" title="Go back to the previous page of results" src="../Images/moveprev.gif" alt="Go back to the previous page of results" /></li>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar2$cmdNext" id="ctl00_ContentPlaceHolder1_NavBar2_cmdNext" title="Go to the next page of results" src="../Images/MoveNext.gif" alt="Go to the next page of results" /></li>
            <li>
                <input type="image" name="ctl00$ContentPlaceHolder1$NavBar2$cmdLast" id="ctl00_ContentPlaceHolder1_NavBar2_cmdLast" title="Go to the last page of results" src="../Images/movelast.gif" alt="Go to the last page of results" /></li>
        </ul>
    </div>
</section>

            </div>
        </div>
        <div style="float: right; width: 30%">
            <h2>Further Search Options</h2>
            <ul>
                <li><a href="Search_MainPageAdv.aspx" title="Use the Advanced Search for more specialised searching">Advanced Search</a></li>
                <li><a href="Search_ById.aspx" title="Search a specific notice ID">Search By Ref</a></li>
                <li><a href="search_7daysResultsList.aspx" title="Display list of notices published in the last 7 days">Last 7 Days</a></li>
                <li><a href="search_30daysResultsList.aspx" title="Display list of notices published in the last 30 days">Last 30 Days</a></li>
                
            </ul>
            <br />
            <h2>Notice Categories</h2>
            
<section class="SearchBox">
    
    <input name="ctl00$ContentPlaceHolder1$Search1$txtSearch" type="text" value="Search for category" id="ctl00_ContentPlaceHolder1_Search1_txtSearch" title="Search for category by keyword" class="Textbox" onfocus="if(this.value==&#39;Search for category&#39;) this.value=&#39;&#39;;" />&nbsp;<input type="button" name="ctl00$ContentPlaceHolder1$Search1$cmdSearch" value="Go" onclick="javascript:__doPostBack(&#39;ctl00$ContentPlaceHolder1$Search1$cmdSearch&#39;,&#39;&#39;)" id="ctl00_ContentPlaceHolder1_Search1_cmdSearch" title="Search for notice categories matching entered keywords" class="Button SubButton" />
</section>





            <ul class="Bullets">
                
                        <li><a href='search_category.aspx?ID=100'
                            title="Agriculture and Food Category">
                            Agriculture and Food
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=110'
                            title="Computer and Related Services Category">
                            Computer and Related Services
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=120'
                            title="Construction and Real Estate Category">
                            Construction and Real Estate
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=130'
                            title="Defence and security Category">
                            Defence and security
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=140'
                            title="Education Category">
                            Education
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=150'
                            title="Energy and Related Services Category">
                            Energy and Related Services
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=160'
                            title="Environment and Sanitation Category">
                            Environment and Sanitation
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=170'
                            title="Finance and Related Services Category">
                            Finance and Related Services
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=180'
                            title="Materials and Products Category">
                            Materials and Products
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=190'
                            title="Mining and Ores Category">
                            Mining and Ores
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=200'
                            title="Other Services Category">
                            Other Services
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=210'
                            title="Printing and Publishing Category">
                            Printing and Publishing
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=220'
                            title="Research and Development Category">
                            Research and Development
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=23'
                            title="Sell2Wales Projects Category">
                            Sell2Wales Projects
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=230'
                            title="Technology and Equipment Category">
                            Technology and Equipment
                        </a></li>
                    
                        <li><a href='search_category.aspx?ID=240'
                            title="Transport and Related Services Category">
                            Transport and Related Services
                        </a></li>
                    
            </ul>
        </div>
    </div>
    <script type="text/javascript">
        addEventListeners('ctl00_ContentPlaceHolder1_NavBar1_drpPageNo', 'ctl00_ContentPlaceHolder1_NavBar2_drpPageNo');
    </script>

        </div>
        
        <div id="Signature">
            <div id="Links">
                <ul class="Horizontal">
                        <li><a href="/sitehelp/help_terms.aspx" accesskey="8">Terms &amp; Conditions</a></li>
                        <li><a href="/sitehelp/help_privacy.aspx">Privacy Policy &amp; Cookies</a></li>
                    <li><a href="/sitehelp/Help_access.aspx" accesskey="0">Accessibility</a></li>
                    
                </ul>
            </div>
            <div id="Copyright">
                    &copy; <a href="http://www.millstreamassociates.co.uk" title="Millstream Associates">Millstream Associates Limited
                        <span id="ctl00_lblYear">2015</span></a>
            </div>
        </div>
    </div>
    </form>
</body>
</html>
