source 'https://rubygems.org'

gem "twitter-bootstrap-rails", '2.2.8'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

gem 'elasticsearch'
gem 'fuzzy_match'

gem 'nokogiri'

gem 'rdf', '~> 1.1.3'
gem 'rdf-turtle', '~> 1.1.3'
gem 'json-ld', '~> 1.1.2'
gem 'json-schema', '~> 2.2.2'
gem 'sparql', '~> 1.1.3', :git => "git://github.com/ruby-rdf/sparql.git", :branch => 'develop'
gem 'json-generator', '~> 0.1.0'
gem 'rdf-rdfxml', '~> 1.1.0.1'
gem 'faker'
gem 'rest-client'
gem 'patron'

gem 'linkedin-scraper'

#group :default do
#  gem 'j2o'
#  gem 'data_extraction'
#end


gem 'j2o', :path => '../json2ontology'
gem 'data_extraction', :path => '../data_extraction'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
#gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

