source 'https://rubygems.org'


gemspec
# Specify your gem's dependencies in j2o.gemspec
gem 'guard-rspec', require: false
gem 'rdf', '~> 1.1.3'
gem 'rdf-turtle', '~> 1.1.3'
gem 'json-ld', '~> 1.1.2'
gem 'json-schema', '~> 2.2.2'
gem 'sparql', '~> 1.1.3',:git => "git://github.com/ruby-rdf/sparql.git", :branch => 'develop'
gem 'json-generator', '~> 0.1.0'
gem 'rdf-rdfxml', '~> 1.1.0.1'
gem 'faker'


